# Ray Tune配置（无需optuna）
ray:
  num_samples: 20
  max_concurrent_trials: 1
  resources_per_trial:
    cpu: 4
    gpu: 2
  
# 搜索空间
search_space:
  lr:
    type: loguniform
    min: 1e-7
    max: 5e-6
  ppo_mini_batch_size:
    type: choice
    values: [16, 32, 64]
  ppo_micro_batch_size:
    type: choice
    values: [8, 16, 24]
  kl_loss_coef:
    type: loguniform
    min: 1e-4
    max: 1e-2
  n_rollouts:
    type: choice
    values: [2, 4, 6]
  kl_coef:
    type: loguniform
    min: 1e-4
    max: 5e-3

# 调度器配置
scheduler:
  type: asha
  max_t: 500
  grace_period: 50
  reduction_factor: 2

# 搜索算法（无需optuna）
search_algorithm:
  type: bayesian
  metric: validation_reward
  mode: max
  random_search_steps: 5

# 日志配置
logging:
  wandb: true
  project_name: "GRPO_ray_tune_no_optuna"
  save_best_config: true