# Ray Tune配置
ray:
  num_samples: 30
  max_concurrent_trials: 2
  resources_per_trial:
    cpu: 8
    gpu: 4
  
# 搜索空间
search_space:
  lr:
    type: loguniform
    min: 1e-7
    max: 1e-5
  ppo_mini_batch_size:
    type: choice
    values: [16, 32, 64, 128]
  ppo_micro_batch_size:
    type: choice
    values: [8, 16, 32]
  kl_loss_coef:
    type: loguniform
    min: 1e-4
    max: 1e-2
  n_rollouts:
    type: choice
    values: [2, 4, 8, 16]
  kl_coef:
    type: loguniform
    min: 1e-4
    max: 1e-2

# 调度器配置
scheduler:
  type: asha
  max_t: 1000
  grace_period: 50
  reduction_factor: 2

# 搜索算法
search_algorithm:
  type: optuna
  metric: validation_reward
  mode: max

# 日志配置
logging:
  wandb: true
  project_name: "GRPO_ray_tune"
  save_best_config: true